[package]
name = "rinha-fraud"
version = "0.1.0"
edition = "2021"
license = "MIT"

[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "build_index"
path = "src/bin/build_index.rs"

[[bin]]
name = "validate"
path = "src/bin/validate.rs"

[lib]
name = "rinha_fraud"
path = "src/lib.rs"

[dependencies]
memmap2 = "0.9"
tiny_http = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["raw_value"] }
flate2 = "1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
